# Generated by Django 3.2.5 on 2021-07-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCom', models.CharField(max_length=50)),
                ('CorreElec', models.EmailField(blank=True, max_length=254, null=True)),
                ('nomUsuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=15)),
            ],
        ),
    ]
